name: Kernel CI Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make scripts executable
      run: |
        chmod +x ./SO_BUILD.sh
        chmod +x ./run.sh

    - name: Build kernel with MM test
      run: |
        echo "Running build script..."
        ./SO_BUILD.sh --test-mm --no-run || {
          echo "::error:: Build script failed. Check logs for details."
          exit 1
        }
        echo "Build completed successfully."

    - name: Run kernel in QEMU and capture output
      run: |
        echo "Running kernel in QEMU..."
        timeout 60s ./run.sh > qemu_output.log 2>&1 || true
        echo "QEMU execution finished (check log for details)."

    - name: Check memory test results
      run: |
        echo "--- QEMU Output Log ---"
        cat qemu_output.log
        echo "-----------------------"

        if grep -q "--- Test del Memory Manager: FAILED ----" qemu_output.log; then
          echo "::error:: Detected memory test failure message in QEMU output."
          exit 1
        elif grep -q "--- Test del Memory Manager: PASSED ----" qemu_output.log; then
          echo "::notice:: Detected memory test success message in QEMU output."
          exit 0
        else
          echo "::warning:: Could not find explicit PASS or FAIL message for Memory Test in QEMU output."
          echo "::warning:: Test outcome is indeterminate or kernel did not reach test conclusion messages."
          echo "::error:: Memory test outcome indeterminate."
          exit 1
        fi